max_linear_vel       : 1.1
max_angular_vel      : 3.141519
gain_p_right         : 1.0
gain_i_right         : 0
gain_d_right         : 0
gain_p_left          : 1.0
gain_i_left          : 0
gain_d_left          : 0
rc_filter_rate       : 0.3
